### ISSUE TITLE
ET: System withdraws an amount less than what the user has requested

### ISSUE THREAD

**Issue by jqvillar** [enochtsang/seng471-assignment1#1]
Function Being Tested: Withdrawal

------------

Build Number: Version Number 1.0

Severity: High

Priority: High

Reported On: 24/01/16 

Reason: Bug

Description:
The system does not withdraw the correct amount that the user has requested for. The system withdraws less than the amount chosen.

Steps To Reproduce:
1) ATM Machine must be turned “ON”
2) Enter 20 for the the number of $20 bills 
3) Click “Click to insert card”
4) Input 1 as the card number
5) Input 42 as the PIN number and click “ENTER”
6) Press 1 to choose the “Withdrawal” option
7) Press 1 or 2 to choose “CHEQUING” or “SAVINGS”
8) Choose to withdraw $200 by pressing 5

------------

Expected result:
The system withdraws the correct amount chosen  by the user; The system displays the correct amount and updated balance; The system correctly records the transaction in the log (this includes the request to the bank and the bank approval)

**Comment by bryson189** [comment]
This issue has been fixed in version 1.1.

**Comment by jqvillar** [comment]
fixed
