### ISSUE TITLE
ET: System does not take and transfer the correct amount that the user has input

### ISSUE THREAD

**Issue by jqvillar** [enochtsang/seng471-assignment1#12]
Function Being Tested: Transfer

------------

Build Number: Version Number 1.0

Severity: High

Priority: High

Reported On: 24/01/16

Reason: Bug

Description:
The system does not transfer the correct amount to the specified bank account. The amount transferred is 50 cents less than the amount that was input by the user. 

Steps To Reproduce:
1) ATM Machine must be turned “ON”
2) Enter 20 for the the number of $20 bills 
3) Click “Click to insert card”
4) Input 1 as the card number
5) Input 42 as the PIN number and click “ENTER”
6) Press 3 to choose the “Transfer” option
7) Press 2 to choose “SAVINGS” to transfer from it
8) Press 1 to choose "CHECKING" to transfer to it
9) Input $10.00 (or any amount) to transfer and press "ENTER"

------------

Expected result:
The system asks the user which account they would like to transfer from and which account they would like to transfer to;The system also asks the user the amount they would like to transfer; The amount that they chose is then transferred between the correct accounts; The system correctly records the transaction in the log (this includes the request to the bank and the bank approval)

**Comment by bryson189** [comment]
Resolved: This issue has been fixed in version 1.1.
