### ISSUE TITLE
ET: System log indicates that the system dispenses $500.00 when a user inquires about an account that is not available to them

### ISSUE THREAD

**Issue by jqvillar** [enochtsang/seng471-assignment1#15]
Function Being Tested: Balance Inquiry

------------

Build Number: Version Number 1.0

Severity: High

Priority: High

Reported On: 24/01/16

Reason: Bug

Description:
The system displays the wrong accounts that are available to the user of that card and if the user tries to inquire about the balance of the account that is not available to them the system displays an, "Unknown Error" and a dispenses $500.00. It shows the ATM dispensing $500.00 from the logs.

Steps To Reproduce:
1) ATM Machine must be turned “ON”
2) Enter 20 for the the number of $20 bills 
3) Click “Click to insert card”
4) Input 1 as the card number
5) Input 42 as the PIN number and click “ENTER”
6) Press 4 to choose the “Balance Inquiry” option
7) Press 2 to choose the "MONEY MARKET" option
8) Press "Show log"

------------

Expected result:
The system should display the correct accounts that are available to the user. For card 1 the available accounts are: Checking and Savings and for card 2 the available accounts are : Checking and Money Market. When an account is chosen the correct balance for that account should be displayed. The transaction should be approved by the bank and correctly saves that transaction in the log.

**Comment by bryson189** [comment]
Resolved: This issue has been fixed in version 1.1.
