### ISSUE TITLE
MFT 8: Would is spelled incorrectly when prompted for another transaction

### ISSUE THREAD

**Issue by kkcmah** [enochtsang/seng471-assignment1#5]
Function Being Tested: Session

------------

Build Number: Version Number 1.0

Severity: Low

Priority: Low

Reported On: 24/01/16

Reason: Bug/Defect

Description:
The system displays "Wood you like to do another transaction?" where "would" is spelled incorrectly as "wood".

Steps To Reproduce:
1) Run ATM system version 1.0
2) Turn the system on by pressing the "ON" button
3) Enter 10 for the the number of $20 bills 
4) Click “Click to insert card”
5) Input 1 as the card number
6) Input 42 as the PIN number and click “ENTER”
7) Press 4 to choose the “Balance Inquiry” option
8) Press 1 to select "Checking"

------------

Expected result:
System asks whether customer wants another transaction.

**Comment by bryson189** [comment]
Resolved: This issue has been fixed in version 1.1.
