### ISSUE TITLE
ET: Keyboard stops working after pressing clear

### ISSUE THREAD

**Issue by enochtsang** [enochtsang/seng471-assignment1#8]
Function Being Tested: Keyboard Controls

------------

Build Number: Version Number 1.0

Reported On: 24/01/16

Description:
After pressing clear, the keyboard controls are no longer functional.

Steps To Reproduce:
1) ATM Machine must be turned “ON”
2) Enter any number for the the number of $20 bills 
3) Click “Click to insert card”
4) Input any card number
5) Press clear
6) Keyboard controls should not work

------------
Expected result:
You should still be able to use your keyboard controls after pressing clear

**Comment by bryson189** [comment]
Resolved: This issue has been fixed in version 1.1.
